# name: actions
# on: push
# jobs:
#   init:
#   runs-on: ubuntu-latest
#   steps:
#   - uses : actions/checkout@v3
#   - name: Starting Node.js${{ matrix.node-version}}
#   uses: actions/setup/node@v3
#   with:
#     node-version: ${{ matrix.node-version}}
#   - name: install modules
#   run: npm install
#   - name: build project
#   run: npm run build
#   - name: run unit tests
#   run: ng test
name: learn-github-actions
# run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install -g bats
      - run: bats -v
  - name: install modules
  run: npm install
  - name: build project
  run: npm run build
  - name: run unit tests
  run: ng test
